//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorteos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int Id { get; set; }
        public string Lote { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string FacturaPath { get; set; }
        public Nullable<int> ProvinciaId { get; set; }
        public Nullable<int> CiudadId { get; set; }
        public Nullable<int> MarcaId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> SorteoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Tipo { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual Sorteo Sorteo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
