//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorteos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sitio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sitio()
        {
            this.Sorteo = new HashSet<Sorteo>();
        }
    
        public int Id { get; set; }
        public string POP { get; set; }
        public string TOS { get; set; }
        public string ClientId { get; set; }
        public string Company { get; set; }
        public string EmailAccount { get; set; }
        public string BaseUrl { get; set; }
        public string PageTitle { get; set; }
        public string FacebookClientId { get; set; }
        public string FacebookSecretKey { get; set; }
        public string FacebookRedirectUri { get; set; }
        public string SendGridApiKey { get; set; }
        public string FacebookLink { get; set; }
        public string InstagramLink { get; set; }
        public string WhatsappLink { get; set; }
        public Nullable<bool> MasterSite { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorteo> Sorteo { get; set; }
    }
}
