//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorteos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sitio
    {
        public int Id { get; set; }
        public string POP { get; set; }
        public string TOS { get; set; }
    }
}
