//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorteos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Compra = new HashSet<Compra>();
            this.Ganador = new HashSet<Ganador>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmado { get; set; }
        public string OtpCode { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<bool> CambioPassword { get; set; }
        public string FacebookAccessToken { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> PerfilId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> BloqueadoHasta { get; set; }
        public Nullable<int> SorteoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ganador> Ganador { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual Sorteo Sorteo { get; set; }
    }
}
